version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../tests/fixtures/mysql/init.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306
    env_file:
      - ../tests/.env.tests
    #environment:
      #MYSQL_USER: 'testuser'
      #MYSQL_PASSWORD: 't3stPass'
      #MYSQL_ROOT_PASSWORD: 't3stPass'
      #MYSQL_DATABASE: 'migration'
  python:
    build:
      context: ../
      dockerfile: ./docker/transpydata/Dockerfile
    volumes: 
      - ../tests/:/code/tests
      - ../transpydata/:/code/transpydata
      - ../bin/wait-for.sh:/code/wait-for.sh
    env_file:
      - ../tests/.env.tests
    command: >
      /bin/sh -c "./wait-for.sh mysql:3306 -t 20 &&
                  pipenv run python -m unittest discover -s tests"
    depends_on:
      - mysql
