# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
      - 'test*'

jobs:
  publish-package:
    # if: github.event.base_ref == 'refs/heads/feature/setup-ci'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev
      - name: Set up test dockers
        run: docker-compose -f docker/docker-compose.test.yml up -d
      - name: Wait for containers
        run: |
          bin/wait-for-it.sh localhost:3306
      - name: Run tests
        run: pipenv run python -m unittest discover -s tests
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: |
          pipenv run python setup.py sdist bdist_wheel
          pipenv run twine upload --repository testpypi dist/*
